name: sdk_103x
version: v0.0.1
description: ""
tag: ""
keywords: 
author:
  name: ""
license: ""
homepage: 
type: sdk
depends:
  - apt32f103x_evb: v0.0.1
  - apt_console: v0.0.0
hw_info:
  cpu_id: ""
  cpu_name: ""
  vendor_name: ""
  chip_name: ""
  board_name: ""
  ld_script: ""
  flash_program: ""
build_config:
  include: 
  internal_include: 
  cflag: ""
  cxxflag: ""
  asmflag: ""
  define: 
  libs: 
  libpath: 
source_file: 
def_config: 
install: 
depends_forward:
  - apt32f103x_evb: v0.0.1
  - apt_console: v0.0.0