name: apt32f103x_demo
version: v0.0.1
description: demo code for reference
tag: ""
keywords: 
author:
  name: ""
license: ""
homepage: 
type: common
depends: 
yoc_version: 
hw_info:
  cpu_id: ""
  cpu_name: ""
  vendor_name: ""
  chip_name: ""
  board_name: ""
  ld_script: ""
  flash_program: ""
build_config:
  include:
    - include
  internal_include: 
  cflag: -O3  -g1
  cxxflag: -O3  -g1
  asmflag: ""
  define: 
  libs: 
  libpath: 
source_file:
  - src/*.c
def_config: 
install: 
depends_forward: 